resolver: lts-8.20

packages:
- '.'
- location:
    git: https://github.com/rybern/prob-seq.git
    commit: 05f983990454ec4f1463c1725e3cdbc888056809
  extra-dep: true
#- '../prob-seq'
- location:
    git: https://github.com/rybern/construction-files.git
    commit: HEAD
  extra-dep: true

extra-deps: [ sparse-lin-alg-0.4.3
            , prob-seq-0.1.0.0
            , vector-0.12.0.0 ]

flags: {}

extra-package-dbs: []
