resolver: lts-9.12

packages:
- '.'
- location:
    git: https://github.com/rybern/prob-seq.git
    commit: 187b848bbbfded1b1d7fd421e448d3344dd7360e
  extra-dep: true
#- '../prob-seq'
- location:
    git: https://github.com/rybern/construction-files.git
    commit: HEAD
  extra-dep: true

extra-deps: [ sparse-lin-alg-0.4.3
            , prob-seq-0.1.0.0
            , vector-0.12.0.0 ]

flags: {}

extra-package-dbs: []

nix:
  packages: [pkgconfig, cairo, zlib, gmp, ncurses, gcc]
